/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CompanyRouteImport } from './routes/company/route'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout/route'
import { Route as WorkspaceRouteImport } from './routes/$workspace/route'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as CompanyDashboardImport } from './routes/company/dashboard'
import { Route as PathlessLayoutSignUpImport } from './routes/_pathlessLayout/sign-up'
import { Route as PathlessLayoutLogInImport } from './routes/_pathlessLayout/log-in'
import { Route as WorkspaceSettingsImport } from './routes/$workspace/settings'
import { Route as WorkspaceQuizImport } from './routes/$workspace/quiz'
import { Route as WorkspaceQuestionsImport } from './routes/$workspace/questions'
import { Route as WorkspaceFormsImport } from './routes/$workspace/forms'
import { Route as WorkspaceDashboardImport } from './routes/$workspace/dashboard'
import { Route as WorkspaceAnalyticsImport } from './routes/$workspace/analytics'

// Create/Update Routes

const CompanyRouteRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutRouteRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceRouteRoute = WorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const CompanyDashboardRoute = CompanyDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompanyRouteRoute,
} as any)

const PathlessLayoutSignUpRoute = PathlessLayoutSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutLogInRoute = PathlessLayoutLogInImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const WorkspaceSettingsRoute = WorkspaceSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

const WorkspaceQuizRoute = WorkspaceQuizImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

const WorkspaceQuestionsRoute = WorkspaceQuestionsImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

const WorkspaceFormsRoute = WorkspaceFormsImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

const WorkspaceDashboardRoute = WorkspaceDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

const WorkspaceAnalyticsRoute = WorkspaceAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$workspace': {
      id: '/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRoute
    }
    '/$workspace/analytics': {
      id: '/$workspace/analytics'
      path: '/analytics'
      fullPath: '/$workspace/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsImport
      parentRoute: typeof WorkspaceRouteImport
    }
    '/$workspace/dashboard': {
      id: '/$workspace/dashboard'
      path: '/dashboard'
      fullPath: '/$workspace/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardImport
      parentRoute: typeof WorkspaceRouteImport
    }
    '/$workspace/forms': {
      id: '/$workspace/forms'
      path: '/forms'
      fullPath: '/$workspace/forms'
      preLoaderRoute: typeof WorkspaceFormsImport
      parentRoute: typeof WorkspaceRouteImport
    }
    '/$workspace/questions': {
      id: '/$workspace/questions'
      path: '/questions'
      fullPath: '/$workspace/questions'
      preLoaderRoute: typeof WorkspaceQuestionsImport
      parentRoute: typeof WorkspaceRouteImport
    }
    '/$workspace/quiz': {
      id: '/$workspace/quiz'
      path: '/quiz'
      fullPath: '/$workspace/quiz'
      preLoaderRoute: typeof WorkspaceQuizImport
      parentRoute: typeof WorkspaceRouteImport
    }
    '/$workspace/settings': {
      id: '/$workspace/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsImport
      parentRoute: typeof WorkspaceRouteImport
    }
    '/_pathlessLayout/log-in': {
      id: '/_pathlessLayout/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof PathlessLayoutLogInImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/sign-up': {
      id: '/_pathlessLayout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PathlessLayoutSignUpImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardImport
      parentRoute: typeof CompanyRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface WorkspaceRouteRouteChildren {
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceFormsRoute: typeof WorkspaceFormsRoute
  WorkspaceQuestionsRoute: typeof WorkspaceQuestionsRoute
  WorkspaceQuizRoute: typeof WorkspaceQuizRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceFormsRoute: WorkspaceFormsRoute,
  WorkspaceQuestionsRoute: WorkspaceQuestionsRoute,
  WorkspaceQuizRoute: WorkspaceQuizRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutLogInRoute: typeof PathlessLayoutLogInRoute
  PathlessLayoutSignUpRoute: typeof PathlessLayoutSignUpRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutLogInRoute: PathlessLayoutLogInRoute,
  PathlessLayoutSignUpRoute: PathlessLayoutSignUpRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

interface CompanyRouteRouteChildren {
  CompanyDashboardRoute: typeof CompanyDashboardRoute
}

const CompanyRouteRouteChildren: CompanyRouteRouteChildren = {
  CompanyDashboardRoute: CompanyDashboardRoute,
}

const CompanyRouteRouteWithChildren = CompanyRouteRoute._addFileChildren(
  CompanyRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteRouteWithChildren
  '': typeof PathlessLayoutRouteRouteWithChildren
  '/company': typeof CompanyRouteRouteWithChildren
  '/$workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/$workspace/dashboard': typeof WorkspaceDashboardRoute
  '/$workspace/forms': typeof WorkspaceFormsRoute
  '/$workspace/questions': typeof WorkspaceQuestionsRoute
  '/$workspace/quiz': typeof WorkspaceQuizRoute
  '/$workspace/settings': typeof WorkspaceSettingsRoute
  '/log-in': typeof PathlessLayoutLogInRoute
  '/sign-up': typeof PathlessLayoutSignUpRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteRouteWithChildren
  '': typeof PathlessLayoutRouteRouteWithChildren
  '/company': typeof CompanyRouteRouteWithChildren
  '/$workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/$workspace/dashboard': typeof WorkspaceDashboardRoute
  '/$workspace/forms': typeof WorkspaceFormsRoute
  '/$workspace/questions': typeof WorkspaceQuestionsRoute
  '/$workspace/quiz': typeof WorkspaceQuizRoute
  '/$workspace/settings': typeof WorkspaceSettingsRoute
  '/log-in': typeof PathlessLayoutLogInRoute
  '/sign-up': typeof PathlessLayoutSignUpRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/company': typeof CompanyRouteRouteWithChildren
  '/$workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/$workspace/dashboard': typeof WorkspaceDashboardRoute
  '/$workspace/forms': typeof WorkspaceFormsRoute
  '/$workspace/questions': typeof WorkspaceQuestionsRoute
  '/$workspace/quiz': typeof WorkspaceQuizRoute
  '/$workspace/settings': typeof WorkspaceSettingsRoute
  '/_pathlessLayout/log-in': typeof PathlessLayoutLogInRoute
  '/_pathlessLayout/sign-up': typeof PathlessLayoutSignUpRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspace'
    | ''
    | '/company'
    | '/$workspace/analytics'
    | '/$workspace/dashboard'
    | '/$workspace/forms'
    | '/$workspace/questions'
    | '/$workspace/quiz'
    | '/$workspace/settings'
    | '/log-in'
    | '/sign-up'
    | '/company/dashboard'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspace'
    | ''
    | '/company'
    | '/$workspace/analytics'
    | '/$workspace/dashboard'
    | '/$workspace/forms'
    | '/$workspace/questions'
    | '/$workspace/quiz'
    | '/$workspace/settings'
    | '/log-in'
    | '/sign-up'
    | '/company/dashboard'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/$workspace'
    | '/_pathlessLayout'
    | '/company'
    | '/$workspace/analytics'
    | '/$workspace/dashboard'
    | '/$workspace/forms'
    | '/$workspace/questions'
    | '/$workspace/quiz'
    | '/$workspace/settings'
    | '/_pathlessLayout/log-in'
    | '/_pathlessLayout/sign-up'
    | '/company/dashboard'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  CompanyRouteRoute: typeof CompanyRouteRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  CompanyRouteRoute: CompanyRouteRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$workspace",
        "/_pathlessLayout",
        "/company",
        "/demo/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$workspace": {
      "filePath": "$workspace/route.tsx",
      "children": [
        "/$workspace/analytics",
        "/$workspace/dashboard",
        "/$workspace/forms",
        "/$workspace/questions",
        "/$workspace/quiz",
        "/$workspace/settings"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout/route.tsx",
      "children": [
        "/_pathlessLayout/log-in",
        "/_pathlessLayout/sign-up"
      ]
    },
    "/company": {
      "filePath": "company/route.tsx",
      "children": [
        "/company/dashboard"
      ]
    },
    "/$workspace/analytics": {
      "filePath": "$workspace/analytics.tsx",
      "parent": "/$workspace"
    },
    "/$workspace/dashboard": {
      "filePath": "$workspace/dashboard.tsx",
      "parent": "/$workspace"
    },
    "/$workspace/forms": {
      "filePath": "$workspace/forms.tsx",
      "parent": "/$workspace"
    },
    "/$workspace/questions": {
      "filePath": "$workspace/questions.tsx",
      "parent": "/$workspace"
    },
    "/$workspace/quiz": {
      "filePath": "$workspace/quiz.tsx",
      "parent": "/$workspace"
    },
    "/$workspace/settings": {
      "filePath": "$workspace/settings.tsx",
      "parent": "/$workspace"
    },
    "/_pathlessLayout/log-in": {
      "filePath": "_pathlessLayout/log-in.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/sign-up": {
      "filePath": "_pathlessLayout/sign-up.tsx",
      "parent": "/_pathlessLayout"
    },
    "/company/dashboard": {
      "filePath": "company/dashboard.tsx",
      "parent": "/company"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
